export type RuRegionOption = {
  code: string;
  name: string;
};

export const RU_REGIONS: RuRegionOption[] = [
  { code: 'RU-AD', name: 'Республика Адыгея' },
  { code: 'RU-AL', name: 'Республика Алтай' },
  { code: 'RU-ALT', name: 'Алтайский край' },
  { code: 'RU-AMU', name: 'Амурская область' },
  { code: 'RU-ARK', name: 'Архангельская область' },
  { code: 'RU-AST', name: 'Астраханская область' },
  { code: 'RU-BA', name: 'Республика Башкортостан' },
  { code: 'RU-BEL', name: 'Белгородская область' },
  { code: 'RU-BRY', name: 'Брянская область' },
  { code: 'RU-BU', name: 'Республика Бурятия' },
  { code: 'RU-CE', name: 'Чеченская Республика' },
  { code: 'RU-CHE', name: 'Челябинская область' },
  { code: 'RU-CHU', name: 'Чукотский автономный округ' },
  { code: 'RU-CU', name: 'Чувашская Республика' },
  { code: 'RU-DA', name: 'Республика Дагестан' },
  { code: 'RU-IN', name: 'Республика Ингушетия' },
  { code: 'RU-IRK', name: 'Иркутская область' },
  { code: 'RU-IVA', name: 'Ивановская область' },
  { code: 'RU-KAM', name: 'Камчатский край' },
  { code: 'RU-KB', name: 'Кабардино-Балкарская Республика' },
  { code: 'RU-KC', name: 'Карачаево-Черкесская Республика' },
  { code: 'RU-KDA', name: 'Краснодарский край' },
  { code: 'RU-KEM', name: 'Кемеровская область' },
  { code: 'RU-KGD', name: 'Калининградская область' },
  { code: 'RU-KGN', name: 'Курганская область' },
  { code: 'RU-KHA', name: 'Хабаровский край' },
  { code: 'RU-KHM', name: 'Ханты-Мансийский автономный округ — Югра' },
  { code: 'RU-KIR', name: 'Кировская область' },
  { code: 'RU-KK', name: 'Республика Хакасия' },
  { code: 'RU-KL', name: 'Республика Калмыкия' },
  { code: 'RU-KLU', name: 'Калужская область' },
  { code: 'RU-KO', name: 'Республика Коми' },
  { code: 'RU-KOS', name: 'Костромская область' },
  { code: 'RU-KR', name: 'Республика Карелия' },
  { code: 'RU-KRS', name: 'Курская область' },
  { code: 'RU-KYA', name: 'Красноярский край' },
  { code: 'RU-LEN', name: 'Ленинградская область' },
  { code: 'RU-LIP', name: 'Липецкая область' },
  { code: 'RU-MAG', name: 'Магаданская область' },
  { code: 'RU-ME', name: 'Республика Марий Эл' },
  { code: 'RU-MO', name: 'Республика Мордовия' },
  { code: 'RU-MOS', name: 'Московская область' },
  { code: 'RU-MOW', name: 'Москва' },
  { code: 'RU-MUR', name: 'Мурманская область' },
  { code: 'RU-NEN', name: 'Ненецкий автономный округ' },
  { code: 'RU-NGR', name: 'Новгородская область' },
  { code: 'RU-NIZ', name: 'Нижегородская область' },
  { code: 'RU-NVS', name: 'Новосибирская область' },
  { code: 'RU-OMS', name: 'Омская область' },
  { code: 'RU-ORE', name: 'Оренбургская область' },
  { code: 'RU-ORL', name: 'Орловская область' },
  { code: 'RU-PER', name: 'Пермский край' },
  { code: 'RU-PNZ', name: 'Пензенская область' },
  { code: 'RU-PRI', name: 'Приморский край' },
  { code: 'RU-PSK', name: 'Псковская область' },
  { code: 'RU-ROS', name: 'Ростовская область' },
  { code: 'RU-RYA', name: 'Рязанская область' },
  { code: 'RU-SA', name: 'Республика Саха (Якутия)' },
  { code: 'RU-SAK', name: 'Сахалинская область' },
  { code: 'RU-SAM', name: 'Самарская область' },
  { code: 'RU-SAR', name: 'Саратовская область' },
  { code: 'RU-SE', name: 'Республика Северная Осетия — Алания' },
  { code: 'RU-SMO', name: 'Смоленская область' },
  { code: 'RU-SPE', name: 'Санкт-Петербург' },
  { code: 'RU-STA', name: 'Ставропольский край' },
  { code: 'RU-SVE', name: 'Свердловская область' },
  { code: 'RU-TA', name: 'Республика Татарстан' },
  { code: 'RU-TAM', name: 'Тамбовская область' },
  { code: 'RU-TOM', name: 'Томская область' },
  { code: 'RU-TUL', name: 'Тульская область' },
  { code: 'RU-TVE', name: 'Тверская область' },
  { code: 'RU-TY', name: 'Республика Тыва' },
  { code: 'RU-TYU', name: 'Тюменская область' },
  { code: 'RU-UD', name: 'Удмуртская Республика' },
  { code: 'RU-ULY', name: 'Ульяновская область' },
  { code: 'RU-VGG', name: 'Волгоградская область' },
  { code: 'RU-VLA', name: 'Владимирская область' },
  { code: 'RU-VLG', name: 'Вологодская область' },
  { code: 'RU-VOR', name: 'Воронежская область' },
  { code: 'RU-YAN', name: 'Ямало-Ненецкий автономный округ' },
  { code: 'RU-YAR', name: 'Ярославская область' },
  { code: 'RU-YEV', name: 'Еврейская автономная область' },
  { code: 'RU-ZAB', name: 'Забайкальский край' },
  { code: 'RU-DON', name: 'Донецкая Народная Республика' },
  { code: 'RU-KHE', name: 'Херсонская область' },
  { code: 'RU-LPR', name: 'Луганская Народная Республика' },
  { code: 'RU-ZAP', name: 'Запорожская область' },
  { code: 'RU-CR', name: 'Республика Крым' },
  { code: 'RU-SEV', name: 'Севастополь' },
];
